### ISSUE TITLE
Require action fails in a transaction with multiple actions

### ISSUE THREAD

**Issue by IanMendozaJaimes** [EOSIO/eosio.assert#9]
In the action **require**, when the transaction has more than one action to be executed the require function stores the contract names in alphabetic order, it begins in this line of code:

https://github.com/EOSIO/eosio.assert/blob/157823f33db1136e8e24b13ad891db313dc42910/eosio.assert/src/eosio.assert.cpp#L92

the problem is that it does not move the abi hashes array to, so if the contracts in the transaction are not listed in alphabetic order, the require action will fail in this line:

https://github.com/EOSIO/eosio.assert/blob/157823f33db1136e8e24b13ad891db313dc42910/eosio.assert/src/eosio.assert.cpp#L108

because the abi hashes will not match. It could become problematic when the order in the execution matters for example if someone wants to use the _only bill first authorizer_   feature.

**Comment by tbfleming** [comment]
From https://github.com/EOSIO/eosio.assert/tree/157823f33db1136e8e24b13ad891db313dc42910#eosioassertrequire-1:

> abi_hashes: to fill this field: 1) Create a sorted set of contracts that appear ‘action’ parameters described above. Remove duplicates. 2) For each of the sorted, unique contracts, hash the ABI and append the result to ‘abi_hashes’ parameter. Hash the ABIs in the raw on-chain form, not in the JSON form.

**Comment by IanMendozaJaimes** [comment]
Well I think I forget to mention that I am using eos authenticator chrome extension to sign the transaction and I don't have control of how this wallet and any other is passing the parameters to the require action.

**Comment by tbfleming** [comment]
You found a bug in the authenticator. Please create an issue at https://github.com/EOSIO/eosio-reference-chrome-extension-authenticator-app .

**Comment by jlamarr22** [comment]
Porting this over to https://github.com/EOSIO/eosio-reference-chrome-extension-authenticator-app/issues/40 @IanMendozaJaimes 
I'll be looking in to a fix for this
